management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    path: /api-docs

api:
  version: 1.0.0
  termsOfService: https://www.crcl.com/terms
  contactName: Chahir Chalouati
  contactEmail: chahir_chalouati@crcl.com
  licenseName: MIT
  licenseUrl: https://opensource.org/licenses/MIT
image-sizes:
  sizes:
    profile_picture:
      width: 170
      height: 170
      name: "profile_picture"
    cover_photo:
      width: 820
      height: 312
      name: "cover_photo"
    shared_image:
      width: 1200
      height: 630
      name: "shared_image"
    shared_link:
      width: 1200
      height: 628
      name: "shared_link"
    event_image:
      width: 1920
      height: 1080
      name: "event_image"
    group_cover_photo:
      width: 1640
      height: 856
      name: "group_cover_photo"
    gramify_story:
      width: 1080
      height: 1920
      name: "gramify_story"
    gramify_ad:
      width: 1200
      height: 628
      name: "gramify_ad"
---
spring:
  config:
    activate:
      on-profile: dev
client:
  authentication:
    url: http://localhost:9999/authentication
    name: authentication
  srvAuthentication:
    url: http://localhost:9999/authentication
    name: srvAuthentication
  storage:
    url: http://localhost:9999/storage
    name: storage
  srvStorage:
    url: http://localhost:9999/storage
    name: srvStorage
  profile:
    url: http://localhost:9999/profile
    name: profile
  srvProfile:
    url: http://localhost:9999/profile
    name: srvProfile
  post:
    url: http://localhost:9999/post
    name: post
  srvPost:
    url: http://localhost:9999/post
    name: srvPost
  comment:
    url: http://localhost:9999/comment
    name: comment
  srvComment:
    url: http://localhost:9999/comment
    name: srvComment
api:
  authorizationUrl: ${client.authentication.url}
  tokenUrl: ${client.authentication.url}/oauth2/token

---
spring:
  config:
    activate:
      on-profile: docker
client:
  authentication:
    url: http://proxy-service:9999/authentication
    name: authentication
  srvAuthentication:
    url: http://proxy-service:9999/authentication
    name: srvAuthentication
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  srvStorage:
    url: http://proxy-service:9999/storage
    name: srvStorage
  profile:
    url: http://proxy-service:9999/profile
    name: profile
  srvProfile:
    url: http://proxy-service:9999/profile
    name: srvProfile
  post:
    url: http://proxy-service:9999/post
    name: post
  srvPost:
    url: http://proxy-service:9999/post
    name: srvPost
  comment:
    url: http://proxy-service:9999/comment
    name: comment
  srvComment:
    url: http://proxy-service:9999/comment
    name: srvComment

api:
  authorizationUrl: ${client.authentication.url}
  tokenUrl: ${client.authentication.url}/oauth2/token

---
spring:
  config:
    activate:
      on-profile: prod
client:
  authentication:
    url: http://proxy-service:9999/authentication
    name: authentication
  srvAuthentication:
    url: http://proxy-service:9999/authentication
    name: srvAuthentication
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  srvStorage:
    url: http://proxy-service:9999/storage
    name: srvStorage
  profile:
    url: http://proxy-service:9999/profile
    name: profile
  srvProfile:
    url: http://proxy-service:9999/profile
    name: srvProfile
  post:
    url: http://proxy-service:9999/post
    name: post
  srvPost:
    url: http://proxy-service:9999/post
    name: srvPost
  comment:
    url: http://proxy-service:9999/comment
    name: comment
  srvComment:
    url: http://proxy-service:9999/comment
    name: srvComment
api:
  authorizationUrl: ${client.authentication.url}
  tokenUrl: ${client.authentication.url}/oauth2/token
