management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /api-docs

define: &swagger-api-metadata
  version: 1.0.0
  termsOfService: https://www.crcl.com/terms
  contactName: Chahir Chalouati
  contactEmail: chahir_chalouati@example.com
  licenseName: MIT
  licenseUrl: https://opensource.org/licenses/MIT

---
spring:
  config:
    activate:
      on-profile: dev
client:
  idp:
    url: http://localhost:9999/idp
    name: idp
  storage:
    url: http://localhost:7010/storage
    name: storage
  srvStorage:
    url: http://localhost:7010/storage
    name: storage
  profile:
    url: http://localhost:7009/profile
    name: profile
  srvProfile:
    url: http://localhost:7009/profile
    name: profile
api:
  authorizationUrl: ${client.idp.url}
  tokenUrl: ${client.idp.url}/oauth2/token
  <<: *swagger-api-metadata
---
spring:
  config:
    activate:
      on-profile: docker
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:7010/storage
    name: storage
  srvStorage:
    url: http://proxy-service:7010/storage
    name: storage
  profile:
    url: http://proxy-service:7009/profile
    name: profile
  srvProfile:
    url: http://proxy-service:7009/profile
    name: profile
api:
  authorizationUrl: ${client.idp.url}
  tokenUrl: ${client.idp.url}/oauth2/token
  <<: *swagger-api-metadata
---
spring:
  config:
    activate:
      on-profile: prod
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:7010/storage
    name: storage
  srvStorage:
    url: http://proxy-service:7010/storage
    name: storage
  profile:
    url: http://proxy-service:7009/profile
    name: profile
  srvProfile:
    url: http://proxy-service:7009/profile
    name: profile
api:
  authorizationUrl: ${client.idp.url}
  tokenUrl: ${client.idp.url}/oauth2/token
  <<: *swagger-api-metadata