---
spring:
  config:
    activate:
      on-profile: dev
client:
  idp:
    url: http://localhost:9999/idp
    name: idp
  storage:
    url: http://localhost:9999/storage
    name: storage
  srvStorage:
    url: http://localhost:9999/storage
    name: storage
  profile:
    url: http://localhost:9999/profile
    name: profile
  srvProfile:
    url: http://localhost:9999/profile
    name: profile
include: common.yaml
---
spring:
  config:
    activate:
      on-profile: docker
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  srvStorage:
    url: http://proxy-service:9999/storage
    name: storage
  profile:
    url: http://proxy-service:9999/profile
    name: profile
  srvProfile:
    url: http://proxy-service:9999/profile
    name: profile
include: common.yaml
---
spring:
  config:
    activate:
      on-profile: prod
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  srvStorage:
    url: http://proxy-service:9999/storage
    name: storage
  profile:
    url: http://proxy-service:9999/profile
    name: profile
  srvProfile:
    url: http://proxy-service:9999/profile
    name: profile
include: common.yaml
