management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            filter: TRACE
---
spring:
  config:
    activate:
      on-profile: dev
client:
  idp:
    url: http://localhost:9999/idp
    name: idp
  storage:
    url: http://localhost:9999/storage
    name: storage
  profile:
    url: http://localhost:9999/profile
    name: profile
---
spring:
  config:
    activate:
      on-profile: docker
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  profile:
    url: http://proxy-service:9999/profile
    name: profile
---
spring:
  config:
    activate:
      on-profile: prod
client:
  idp:
    url: http://proxy-service:9999/idp
    name: idp
  storage:
    url: http://proxy-service:9999/storage
    name: storage
  profile:
    url: http://proxy-service:9999/profile
    name: profile