server:
  port: 7003
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    cassandra:
      port: 9042
      keyspace-name: audit_dev
      contact-points: localhost
      local-datacenter: datacenter1
      schema-action: create_if_not_exists


