server:
  port: 7003
# openApi documentation
api:
  title: Audit Service
  description: API for Audit services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_audit
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          audit-service-oidc:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          audit-service:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_audit
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          audit-service-oidc:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          audit-service:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_audit
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          audit-service-oidc:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          audit-service:
            provider: spring
            client-id: story-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000