server:
  port: 7003
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    cassandra:
      port: 9042
      keyspace-name: audit_dev
      contact-points: localhost
      local-datacenter: datacenter1
      schema-action: create_if_not_exists
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    cassandra:
      port: 9042
      keyspace-name: audit_dev
      contact-points: cassandra
      local-datacenter: datacenter1
      schema-action: create_if_not_exist
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    cassandra:
      port: 9042
      keyspace-name: audit_dev
      contact-points: cassandra
      local-datacenter: datacenter1
      schema-action: create_if_not_exist
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
