server:
  port: 7003
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: audit_dev
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: audit_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: audit_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
