server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: authentication_dev
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  clientsProps:
    post-client:
      name: post-service
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      name: proxy-service
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      name: order-service
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      name: ui-client
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      name: notification-service
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    storage_client:
      name: storage-service
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: authentication_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  clientsProps:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: authentication_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  clientsProps:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
