server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: authentication_dev
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  registrations:
    notification-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: notification-service
      uri: http://127.0.0.1:7008
      scopes:
        - openid
      grantTypes:
        - client_credentials
    post-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: post-service
      uri: http://127.0.0.1:7005
      scopes:
        - openid
      grantTypes:
        - client_credentials
    configuration-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: configuration-service
      uri: http://127.0.0.1:8888
      scopes:
        - openid
      grantTypes:
        - client_credentials
    order-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: order-service
      uri: http://127.0.0.1:7001
      scopes:
        - openid
      grantTypes:
        - client_credentials
    authentication-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: authentication-service
      uri: http://127.0.0.1:9000
      scopes:
        - openid
      grantTypes:
        - client_credentials
    audit-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: audit-service
      uri: http://127.0.0.1:7003
      scopes:
        - openid
      grantTypes:
        - client_credentials
    profile-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: profile-service
      uri: http://127.0.0.1:7009
      scopes:
        - openid
      grantTypes:
        - client_credentials
    storage-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: storage-service
      uri: http://127.0.0.1:7010
      scopes:
        - openid
      grantTypes:
        - client_credentials
    ui-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: ui-service
      uri: http://127.0.0.1:4200
      scopes:
        - openid
      grantTypes:
        - authorization_code
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: authentication_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  registrations:
    notification-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: notification-service
      uri: http://notification-service:7008
      scopes:
        - openid
      grantTypes:
        - client_credentials
    post-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: post-service
      uri: http://post-service:7005
      scopes:
        - openid
      grantTypes:
        - client_credentials
    configuration-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: configuration-service
      uri: http://configuration-service:8888
      scopes:
        - openid
      grantTypes:
        - client_credentials
    order-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: order-service
      uri: http://order-service:7001
      scopes:
        - openid
      grantTypes:
        - client_credentials
    authentication-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: authentication-service
      uri: http://authentication-service:9000
      scopes:
        - openid
      grantTypes:
        - client_credentials
    audit-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: audit-service
      uri: http://audit-service:7003
      scopes:
        - openid
      grantTypes:
        - client_credentials
    profile-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: profile-service
      uri: http://profile-service:7009
      scopes:
        - openid
      grantTypes:
        - client_credentials
    storage-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: storage-service
      uri: http://storage-service:7010
      scopes:
        - openid
      grantTypes:
        - client_credentials
    ui-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: ui-service
      uri: http://storage-service:4200
      scopes:
        - openid
      grantTypes:
        - authorization_code

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: authentication_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /idp/login
  failureForwardUrl: /idp/login?error=true
  registration:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
