server:
  port: 9000
# openApi documentation
api:
  title: Authentication Service
  description: API for authentication services
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_authentication
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations:
    notification-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: notification-service
      uris:
        - http://127.0.0.1:7008
      scopes:
        - openid
      grantTypes:
        - client_credentials
    post-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: post-service
      uris:
        - http://127.0.0.1:7005
      scopes:
        - openid
      grantTypes:
        - client_credentials
    configuration-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: configuration-service
      uris:
        - http://127.0.0.1:8888
      scopes:
        - openid
      grantTypes:
        - client_credentials
    comment-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: comment-service
      uris:
        - http://127.0.0.1:7001
      scopes:
        - openid
      grantTypes:
        - client_credentials
    authentication-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: authentication-service
      uris:
        - http://127.0.0.1:9000
      scopes:
        - openid
      grantTypes:
        - client_credentials
    audit-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: audit-service
      uris:
        - http://127.0.0.1:7003
      scopes:
        - openid
      grantTypes:
        - client_credentials
    profile-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: profile-service
      uris:
        - http://127.0.0.1:7009
      scopes:
        - openid
      grantTypes:
        - client_credentials
    storage-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: storage-service
      uris:
        - http://127.0.0.1:7010
      scopes:
        - openid
      grantTypes:
        - client_credentials
    ui-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: ui-service
      uris:
        - http://127.0.0.1:4200
      scopes:
        - openid
      grantTypes:
        - authorization_code
        - client_credentials
minio:
  access-key: myaccesskey
  url: http://localhost:47017
  secret-key: mysecretkey
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false
dummy:
  username: username
  password: password
  count: 100
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: authentication_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations: &registrations
    notification-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: notification-service
      uris:
        - http://notification-service:7008
      scopes:
        - openid
      grantTypes:
        - client_credentials
    post-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: post-service
      uris:
        - http://post-service:7005
      scopes:
        - openid
      grantTypes:
        - client_credentials
    configuration-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: configuration-service
      uris:
        - http://configuration-service:8888
      scopes:
        - openid
      grantTypes:
        - client_credentials
    comment-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: comment-service
      uris:
        - http://comment-service:7001
      scopes:
        - openid
      grantTypes:
        - client_credentials
    authentication-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: authentication-service
      uris:
        - http://authentication-service:9000
      scopes:
        - openid
      grantTypes:
        - client_credentials
    audit-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: audit-service
      uris:
        - http://audit-service:7003
      scopes:
        - openid
      grantTypes:
        - client_credentials
    profile-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: profile-service
      uris:
        - http://profile-service:7009
      scopes:
        - openid
      grantTypes:
        - client_credentials
    storage-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: storage-service
      uris:
        - http://storage-service:7010
      scopes:
        - openid
      grantTypes:
        - client_credentials
    ui-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: ui-service
      uris:
        - http://ui-service:4200
      scopes:
        - openid
      grantTypes:
        - authorization_code
        - client_credentials
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: authentication_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
mongock:
  change-logs-scan-package: com.crcl.authentication.migration
security:
  clientIp: 127.0.0.1
  issuer: http://authentication-service:9000
  loginPage: /authentication/login
  certificationBucket: cert
  failureForwardUrl: /authentication/login?error=true
  registrations:
    notification-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: notification-service
      uris:
        - http://notification-service:7008
      scopes:
        - openid
      grantTypes:
        - client_credentials
    post-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: post-service
      uris:
        - http://post-service:7005
      scopes:
        - openid
      grantTypes:
        - client_credentials
    configuration-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: configuration-service
      uris:
        - http://configuration-service:8888
      scopes:
        - openid
      grantTypes:
        - client_credentials
    comment-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: comment-service
      uris:
        - http://comment-service:7001
      scopes:
        - openid
      grantTypes:
        - client_credentials
    authentication-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: authentication-service
      uris:
        - http://authentication-service:9000
      scopes:
        - openid
      grantTypes:
        - client_credentials
    audit-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: audit-service
      uris:
        - http://audit-service:7003
      scopes:
        - openid
      grantTypes:
        - client_credentials
    profile-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: profile-service
      uris:
        - http://profile-service:7009
      scopes:
        - openid
      grantTypes:
        - client_credentials
    storage-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: storage-service
      uris:
        - http://storage-service:7010
      scopes:
        - openid
      grantTypes:
        - client_credentials
    ui-service:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
      id: ui-service
      uris:
        - http://ui-service:4200
      scopes:
        - openid
      grantTypes:
        - authorization_code
        - client_credentials
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: key-public-cert
      objectLock: false
      isDefault: true
    - name: key-private-cert
      objectLock: false
      isDefault: false
