server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: authentication_dev
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.crcl.authenticationservice.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  clientsProps:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: authentication_test
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.crcl.authenticationservice.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  clientsProps:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: authentication_test
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.crcl.authenticationservice.migration
security:
  clientIp: 127.0.0.1
  issuer: http://auth-server:9000
  clientsProps:
    post-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    proxy-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    order-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    ui-client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
    notification_client:
      refresh-token-access-time-to-leave: 8000
      token-access-time-to-leave: 8000
