server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: authentication_dev
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.code.dremear.authenticationservice.migration
security:
  issuer: http://auth-server:9000
  clientsProps:
    product-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    proxy-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    order-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    product-ui:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    notification_client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: authentication_test
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.code.dremear.authenticationservice.migration
security:
  issuer: http://auth-server:9000
  clientsProps:
    product-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    proxy-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    order-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    product-ui:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    notification_client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: authentication_test
      host: localhost
      port: 27017
      authentication-database: admin
mongock:
  change-logs-scan-package: com.code.dremear.authenticationservice.migration
security:
  issuer: http://auth-server:9000
  clientsProps:
    product-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    proxy-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    order-client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    product-ui:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500
    notification_client:
      refresh-token-access-time-to-leave: 5000
      token-access-time-to-leave: 500