server:
  port: 7008
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: notification_test
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          notification-client-oidc:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-client-oidc
          notification-client-authorization-code:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: profile.read,profile.write
            client-name: notification-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: "mail@mail.com"
  password: "password"
  defaultEncoding: "UTF-8"
  auth: true
  debug: true
  enable-tls: true
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: notification_test
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-client-oidc:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-client-oidc
          notification-client-authorization-code:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: profile.read,profile.write
            client-name: notification-client-authorization-code
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: notification_test
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-client-oidc:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-client-oidc
          notification-client-authorization-code:
            provider: spring
            client-id: notification-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: profile.read,profile.write
            client-name: notification-client-authorization-code
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
