---
server:
  port: 7008
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: notification_test
      host: localhost
      port: 27017
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        security: trace
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
---
server:
  port: 7008
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: notification_test
      host: mongo
      port: 27017
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        security: trace
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
---
server:
  port: 7008
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: notification_test
      host: mongo
      port: 27017
      authentication-database: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        security: trace
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true