server:
  port: 7008

springfox:
  documentation:
    swagger-ui:
      path: /swagger-ui/index.html
    base-path: /api-docs
    api-info:
      title: Example API
      version: 1.0
      description: Example API Description
    host: example.com
    schemes:
      - http
      - https
    paths-to-exclude:
      - /error.*
    enable: true
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_notification
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://auth-server:9000
mail:
  protocol: "smtp"
  host: "smtp.mailosaur.net"
  port: 25
  username: "w1clmwei@mailosaur.net"
  password: "{cipher}e0770e7cb7806f8bb10621d3274065746ec679b1672775e2cd45432ab1595d77d73177e25ca59f109e147bafb3ec31c54b8e8d277b629579e06c462085e8afe0"
  defaultEncoding: "UTF-8"
  auth: true
  debug: true
  enable-tls: false
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_notification
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_notification
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
