server:
  port: 7008

springfox:
  documentation:
    swagger-ui:
      path: /swagger-ui/index.html
    base-path: /api-docs
    api-info:
      title: Example API
      version: 1.0
      description: Example API Description
    host: example.com
    schemes:
      - http
      - https
    paths-to-exclude:
      - /error.*
    enable: true
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: notification_docker
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://auth-server:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: "mail@mail.com"
  password: "password"
  defaultEncoding: "UTF-8"
  auth: true
  debug: true
  enable-tls: true
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: notification_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: notification_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          notification-service-oidc:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: notification-service-oidc
          notification-service:
            provider: spring
            client-id: notification-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: notification.read,notification.write
            client-name: notification-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
mail:
  protocol: "smtp"
  host: "smtp.gmail.com"
  port: 587
  username: ""
  password: ""
  defaultEncoding: ""
  auth: true
  debug: true
  enable-tls: true
