server:
  port: 7005
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_product?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 50
        cache:
          use_second_level_cache: false
          use_query_cache: false
  sql:
    init:
      continue-on-error: true
      platform: MySQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          product-client-oidc:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: product-client-oidc
          product-client-authorization-code:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://127.0.0.1:7005/authorized"
            scope: product.read
            client-name: product-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql-db:3306/docker_product?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 50
        cache:
          use_second_level_cache: false
          use_query_cache: false
  sql:
    init:
      continue-on-error: true
      platform: MySQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          product-client-oidc:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: product-client-oidc
          product-client-authorization-code:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://product-service:7005/authorized"
            scope: product.read
            client-name: product-client-authorization-code
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysql-db:3306/prod_product?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        generate_statistics: false
        order_inserts: true
        jdbc:
          batch_size: 50
        cache:
          use_second_level_cache: false
          use_query_cache: false
  sql:
    init:
      continue-on-error: true
      platform: MySQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          product-client-oidc:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: product-client-oidc
          product-client-authorization-code:
            provider: spring
            client-id: product-client
            client-secret: secret
            authorization-grant-type: client_credentials
            redirect-uri: "http://product-service:7005/authorized"
            scope: product.read
            client-name: product-client-authorization-code
        provider:
          spring:
            issuer-uri: http://authentication-service:9000

