server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes:
        - id: post-service
          uri: http://127.0.0.1:7005
          predicates:
            - Path=/post/**
        - id: configuration-service
          uri: http://127.0.0.1:8888
          predicates:
            - Path=/config/**
        - id: comment-service
          uri: http://127.0.0.1:7001
          predicates:
            - Path=/comment/**
        - id: story-service
          uri: http://127.0.0.1:7002
          predicates:
            - Path=/story/
        - id: authentication-service
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/authentication/**
        - id: audit-service
          uri: http://127.0.0.1:7003
          predicates:
            - Path=/audit/**
        - id: profile-service
          uri: http://127.0.0.1:7009
          predicates:
            - Path=/profile/**
        - id: storage-service
          uri: http://127.0.0.1:7010
          predicates:
            - Path=/storage/**
        - id: notification-service
          uri: http://127.0.0.1:7008
          predicates:
            - Path=/notification/**
        - id: webSocket-service
          uri: ws://127.0.0.1:61613
          predicates:
            - Path=/ws/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes:
        - id: notification-service
          uri: http://notification-service:7008
          predicates:
            - Path=/profile/
        - id: post-service
          uri: http://post-service:7005
          predicates:
            - Path=/post/
        - id: configuration-service
          uri: http://configuration-service:8888
          predicates:
            - Path=/config/
        - id: comment-service
          uri: http://comment-service:7001
          predicates:
            - Path=/comment/
        - id: story-service
          uri: http://story-service:7002
          predicates:
            - Path=/story/
        - id: authentication-service
          uri: http://authentication-service:9000
          predicates:
            - Path=/authentication/
        - id: audit-service
          uri: http://audit-service:7003
          predicates:
            - Path=/audit/**
        - id: profile-service
          uri: http://profile-service:7009
          predicates:
            - Path=/profile/**
        - id: storage-service
          uri: http://storage-service:7010
          predicates:
            - Path=/storage/**
        - id: notification-service
          uri: http://notification-service:7008
          predicates:
            - Path=/notification/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowed-origin-patterns:
              - "*"
      routes:
        - id: notification-service
          uri: http://notification-service:7008
          predicates:
            - Path=/notification/
        - id: post-service
          uri: http://post-service:7005
          predicates:
            - Path=/post/
        - id: configuration-service
          uri: http://configuration-service:8888
          predicates:
            - Path=/config/
        - id: comment-service
          uri: http://comment-service:7001
          predicates:
            - Path=/comment/
        - id: story-service
          uri: http://story-service:7002
          predicates:
            - Path=/story/
        - id: authentication-service
          uri: http://authentication-service:9000
          predicates:
            - Path=/authentication/
        - id: audit-service
          uri: http://audit-service:7003
          predicates:
            - Path=/audit/**
        - id: profile-service
          uri: http://profile-service:7009
          predicates:
            - Path=/profile/**
        - id: storage-service
          uri: http://storage-service:7010
          predicates:
            - Path=/storage/**
        - id: notification-service
          uri: http://notification-service:7008
          predicates:
            - Path=/notification/**
  security:
    oauth2:
      client:
        registration:
          proxy-service-oidc:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-service:
            provider: spring
            client-id: proxy-service
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
