server:
  port: 9999
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - PUT
              - POST
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: post-service
          uri: http://127.0.0.1:7005
          predicates:
            - Path=/post/**
        - id: configuration-service
          uri: http://127.0.0.1:8888
          predicates:
            - Path=/config/**
        - id: order-service
          uri: http://127.0.0.1:7001
          predicates:
            - Path=/order/**
        - id: authentication-service
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/Oauth/**
        - id: audit-service
          uri: http://127.0.0.1:7003
          predicates:
            - Path=/audit/**
        - id: youtube-service
          uri: https://www.youtube.com
          predicates:
            - Path=/youtube/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          proxy-client-oidc:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-client-authorization-code:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://notification-service:7008
          predicates:
            - Path=/profile/
        - id: post-service
          uri: http://post-service:7005
          predicates:
            - Path=/post/
        - id: configuration-service
          uri: http://configuration-service:8888
          predicates:
            - Path=/config/
        - id: order-service
          uri: http://order-service:7001
          predicates:
            - Path=/order/
        - id: authentication-service
          uri: http://authentication-service:9000
          predicates:
            - Path=/Oauth/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          proxy-client-oidc:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-client-authorization-code:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://notification-service:7008
          predicates:
            - Path=/profile/
        - id: post-service
          uri: http://post-service:7005
          predicates:
            - Path=/post/
        - id: configuration-service
          uri: http://configuration-service:8888
          predicates:
            - Path=/config/
        - id: order-service
          uri: http://order-service:7001
          predicates:
            - Path=/order/
        - id: authentication-service
          uri: http://authentication-service:9000
          predicates:
            - Path=/oauth2/
            - Path=/auth/
  security:
    oauth2:
      client:
        registration:
          proxy-client-oidc:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
          proxy-client-authorization-code:
            provider: spring
            client-id: proxy-client
            client-secret: secret
            authorization-grant-type: client_credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000
