server:
  port: 7010

api:
  title: Storage Service
  description: API for Storage services

image-sizes:
  sizes:
    profile_picture:
      width: 170
      height: 170
      name: "profile picture"
    cover_photo:
      width: 820
      height: 312
      name: "cover photo"
    shared_image:
      width: 1200
      height: 630
      name: "shared image"
    shared_link:
      width: 1200
      height: 628
      name: "shared link"
    event_image:
      width: 1920
      height: 1080
      name: "event image"
    group_cover_photo:
      width: 1640
      height: 856
      name: "group cover photo"
    gramify_story:
      width: 1080
      height: 1920
      name: "gramify story"
    gramify_ad:
      width: 1200
      height: 628
      name: "gramify ad"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: dev_storage
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://localhost:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false
image-sizes:
  sizes:
    profile_picture:
      width: 170
      height: 170
      name: "profile picture"
    cover_photo:
      width: 820
      height: 312
      name: "cover photo"
    shared_image:
      width: 1200
      height: 630
      name: "shared image"
    shared_link:
      width: 1200
      height: 628
      name: "shared link"
    event_image:
      width: 1920
      height: 1080
      name: "event image"
    group_cover_photo:
      width: 1640
      height: 856
      name: "group cover photo"
    gramify_story:
      width: 1080
      height: 1920
      name: "gramify story"
    gramify_ad:
      width: 1200
      height: 628
      name: "gramify ad"
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: docker_storage
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: prod_storage
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false
image-sizes:
  sizes:
    profile_picture:
      width: 170
      height: 170
      name: "profile picture"
    cover_photo:
      width: 820
      height: 312
      name: "cover photo"
    shared_image:
      width: 1200
      height: 630
      name: "shared image"
    shared_link:
      width: 1200
      height: 628
      name: "shared link"
    event_image:
      width: 1920
      height: 1080
      name: "event image"
    group_cover_photo:
      width: 1640
      height: 856
      name: "group cover photo"
    gramify_story:
      width: 1080
      height: 1920
      name: "gramify story"
    gramify_ad:
      width: 1200
      height: 628
      name: "gramify ad"