server:
  port: 7010

api:
  title: Storage Service
  description: API for Storage services

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/swagger-ui.html
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      database: storage_dev
      host: localhost
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
          jwk-set-uri: http://auth-server:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://auth-server:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://localhost:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false
---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      database: storage_docker
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false
---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      database: storage_prod
      host: mongo
      port: 27017
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authentication-service:9000
          jwk-set-uri: http://authentication-service:9000/oauth2/jwks
      client:
        registration:
          storage-service-oidc:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid
            client-name: storage-service-oidc
          storage-service:
            provider: spring
            client-id: storage-service
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: storage.read,storage.write
            client-name: storage-service
        provider:
          spring:
            issuer-uri: http://authentication-service:9000
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      location: ${java.io.tmpdir}
      enabled: true
minio:
  access-key: myaccesskey
  url: http://minio:47017
  secret-key: mysecretkey
  buckets:
    - name: storage
      objectLock: false
      isDefault: true
    - name: video
      objectLock: false
      isDefault: false